name: coveralls-ruby
on: ["push","pull_request"]
jobs:
  build-and-test-with-coverage:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      COVERALLS_PARALLEL: true
      COVERALLS_FLAG_NAME: run-${{ matrix.ruby }}
      COVERALLS_REPO_TOKEN: ndtJXNcp7hKpvcXmdJfCKKgy01qsvrhNk
    strategy:
      matrix:
        ruby: [2.3]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake

  finish-coverage:
    needs: build-and-test-with-coverage
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      COVERALLS_PARALLEL: true
      COVERALLS_REPO_TOKEN: ndtJXNcp7hKpvcXmdJfCKKgy01qsvrhNk
    steps:
      - name: Coveralls Finished
        run: curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$GITHUB_RUN_ID&payload[status]=done"
