name: coveralls-ruby
on: ["push","pull_request"]
jobs:
  build-and-test-with-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.5]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle exec rake
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.0
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.github_token }}
          parallel: true
          flag-name: run-${{ matrix.ruby }}

  finish-coverage:
    needs: build-and-test-with-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.1.0
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
